### ISSUE TITLE
Map Activity won't open

### ISSUE THREAD

**Issue by madhav0922** [ketanchoyal/theParker#1]
Hey dev, 
I have everything upto date and androidx is implemented. The build compiles successfully but,

1. I am not able to get map activity or the location pins to point somewhere, it's like the map activity is there but won't show or find location (location is on and permissions are granted.)
Do i have to add some places through Admin App?

2. In the Admin App, the finish button in the E-wallet does not function and i cannot proceed further. Can you please help.

**Comment by madhav0922** [comment]
I think some code is missing as well, in file Form_LayoutActivity2 file. Maybe it did not upload, which is why the Finish button in E-Wallet does not work.
Can you please update the repo.
I will be very thankful.

**Comment by ketanchoyal** [comment]
Hey sorry for late reply but Map activity won't work until you add your api key

**Comment by ketanchoyal** [comment]
And it will be better if you use your json file for testing as well because I'm soon going to delete my firebase database

**Comment by RICHIN3** [comment]
Hi could you possible to send me the Firebase rules and its database json file

**Comment by madhav0922** [comment]
Hi the map activity issue got solved, had to get the api key and i am using my own firebase database. Never used yours maybe thats why facing another problem that when a booking is made then, i am unable to check previous booking i.e. previous booking list is empty, i'll attach my database and point of error screenshot soon.

**Comment by ketanchoyal** [comment]
> Hi could you possible to send me the Firebase rules and its database json file

Actually you can't use my json files as it is linked to my personal firebase account

**Comment by ketanchoyal** [comment]
> Hi the map activity issue got solved, had to get the api key and i am using my own firebase database. Never used yours maybe thats why facing another problem that when a booking is made then, i am unable to check previous booking i.e. previous booking list is empty, i'll attach my database and point of error screenshot soon.

That won't work because that part was never completed, I'll try to implement that part whenever I get time

**Comment by RICHIN3** [comment]
But from that rules only the app can run for me. without fb rule it won't
work. and if fb json have it will be easier to run the app

**Comment by ketanchoyal** [comment]
here is json of my database

and fb rule is : 

{
  "rules": {
    ".read": true,
    ".write": true
  }
}

[theparker-ed06b-export.json.txt](https://github.com/ketanchoyal/theParker/files/4150705/theparker-ed06b-export.json.txt)

**Comment by RICHIN3** [comment]
Thank for your support!🙂

**Comment by madhav0922** [comment]
Alright ketan, thanks alot for you help and support! Appreciate it
